### ISSUE TITLE
running KITTI  example  failed

### ISSUE THREAD

**Issue by afei26579** [uber/xviz#535] opened 2019-10-16 07:38 UTC
when I use : 
`./scripts/run-kitti-example.sh`
it work,
`# XVIZ Server started.`
`# Ctrl-c to terminate.`
`# xvizserver-log: Listening on port 8080`
but i open browser by http://localhost:8080/  ,it return:

"Upgrade Required"

what should I do ？
node version is 12.12
and apt update done.

**Comment by balag3** [comment] 2019-10-16 09:47
What happens here is that on http://localhost:8080 a websocket server is serving your data and the server tells you that it is missing an UPGRADE header from your browser request.
You need a client that is capable of opening a websocket connection. XVIZLiveLoader is one of them provided by xviz.
I personally use this extension: https://chrome.google.com/webstore/detail/websocket-test-client/fgponpodhbmadfljofbimhhlengambbn?hl=en  
Also what is missing from the description the address should be  ws://localhost:8080/

**Comment by twojtasz** [comment] 2019-10-18 16:32
@afei26579 This is an XVIZ *WebSocket* Server, not an HTTP Server.

To view this follow the *Quick Start* instructions on this page
https://github.com/uber/streetscape.gl

But replace `yarn start` with `yarn start-streaming-local` and it should work.

**Comment by afei26579** [comment] 2019-10-28 09:09
thanks lots . 

> @afei26579 This is an XVIZ _WebSocket_ Server, not an HTTP Server.
> 
> To view this follow the _Quick Start_ instructions on this page
> https://github.com/uber/streetscape.gl
> 
> But replace `yarn start` with `yarn start-streaming-local` and it should work.

thanks a lot.
a new question，i run sush : yarn start-ttreaming-local 
the Command log:
   
![图片](https://user-images.githubusercontent.com/56626114/67665780-63c0a380-f9a5-11e9-84b9-4b9a85e1c462.png)
and browser :   
![图片](https://user-images.githubusercontent.com/56626114/67665907-9a96b980-f9a5-11e9-9a60-407e1d901eba.png)

**Comment by twojtasz** [comment] 2019-10-28 17:43
@afei26579 Can you expand the error with the text "TypeError: can't convert null to object" . I have not seen this and am not sure where the issue is.  By expanding hopefully it will show the file and line.  If it says something like `bundle....` then it is not using source maps.  So try to click on the link on the right so I can try to get context on where this is happening.

**Comment by twojtasz** [comment] 2019-12-10 13:32
@afei26579 fixed in https://github.com/uber/xviz/pull/560

**Closed by twojtasz** 2019-12-10 13:32 UTC
